executor: "KubernetesExecutor"
env: 
 - name: "AIRFLOW_CONN_AIRFLOW_S3_CONN"
   value: "s3://?aws_access_key_id=&aws_secret_access_key="
 - name: "AIRFLOW__CORE__REMOTE_LOGGING"
   value: "True"
 - name: "AIRFLOW__CORE__REMOTE_LOG_CONN_ID"
   value: "airflow_s3_conn"
 - name: "AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER"
   value: "s3://sample-220161"

webserver:
    replicas: 2
    service:
        type: LoadBalancer
dags:
    gitSync:
        enabled: true
        repo: https://github.com/technoavengers/airflow-training.git
        branch: main
        subPath: "dags"
        
        
    
