executor: "KubernetesExecutor"
env: 
 - name: "AIRFLOW_CONN_AIRFLOW_S3_CONN"
   value: "s3://?aws_access_key_id=<access_key>&aws_secret_access_key=<secret_key>"
 - name: "AIRFLOW__CORE__REMOTE_LOGGING"
   value: "True"
 - name: "AIRFLOW__CORE__REMOTE_LOG_CONN_ID"
   value: "aws_s3_conn"
 - name: "AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER"
   value: "s3://sample-220161"
 - name: "AIRFLOW__SECRETS_BACKEND"
   value: "airflow.contrib.secrets.aws_secret_manager.SecretsManagerBackend"
 - name: "AIRFLOW__SECRETS_BACKEND_KWARGS"
   value: "{'connections_prefix': 'airflow/connections'}"

webserver:
    replicas: 2
    service:
        type: LoadBalancer
dags:
    gitSync:
        enabled: true
        repo: https://github.com/technoavengers/airflow-training.git
        branch: main
        subPath: "dags"
        
secret:
    - envName: "AWS_DEFAULT_REGION"
      secretName: "airflow-secret-backend"
      secretKey: "aws-default-region"
    - envName: "AWS_ACCESS_KEY_ID"
      secretName: "airflow-secret-backend"
      secretKey: "aws-access-key-id"
    - envName: "AWS_SECRET_ACCESS_KEY"
      secretName: "airflow-secret-backend"
      secretKey: "aws-secret-access-key"
        
        
    
